// **********************************************************************************
// ** Include for cydWeeWX project to allow WOKWi simulation
// ** See https://wokwi.com documentation for details on setting up WOKWi for VS Code.
// ** This file contains a large JSON document to simulate WeeWX queries.
// **********************************************************************************
// ** Project details at https://github.com/hcomet/cydWeeWX
// ** (c) Copyright Stephen Hillier 2024. All Rights Reserved.
// **********************************************************************************

bool cydWeeWXWokiIsDay = true;
char cydWeeWXWokwiJSON[] = "{"
                            "\"station\":"
                                        "{"
                                        "\"location\": \"Greenwich\","
                                        "\"latitude\": 51.479,"
                                        "\"longitude\": -0,"
                                        "\"altitude (meters)\": 43.0,"
                                        "\"link\": \"\""
                                        "},"
                            "\"almanac\":"
                                        "{"
                                        "\"sunrise\":\"07:36:04\","
                                        "\"sunset\":\"15:58:08\","
                                        "\"twilight start\" : \"07:01:55\","
                                        "\"twilight end\" : \"16:33:16\","
                                        "\"is day\": 1,"
                                        "\"moonrise\":\"02:20:18\","
                                        "\"moonset\":\"13:53:17\","
                                        "\"moon phase\":\"Waning crescent\","
                                        "\"moon fullness\": 18,"
                                        "\"moon waxing\": 0,"
                                        "\"moon phase icon\": 7"
                                        "},"
                            "\"generation\":"
                                        "{"
                                        "\"time\": \"2024-11-26T12:40:00-0000\","
                                        "\"generator\": \"weewx 5.1.0\""
                                        "},"
                            "\"current\":"
                                        "{"
                                        "\"temperature\": {\"value\": 1.546666666666666, \"units\": \"°C\"},"
                                        "\"temperature trend\": {\"value\": 0.43333333333333, \"units\": \"°C\"},"
                                        "\"app temperature\": {\"value\": -0.31333758131720224, \"units\": \"°C\"},"
                                        "\"app temperature trend\": {\"value\": 0.5207760021208901, \"units\": \"°C\"},"
                                        "\"dewpoint\": {\"value\": 0.8335927712495838, \"units\": \"°C\"},"
                                        "\"dewpoint trend\": {\"value\": 0.5768103727577136, \"units\": \"°C\"},"
                                        "\"humidity\": {\"value\": 95.0, \"units\": \"%\"},"
                                        "\"humidity trend\": {\"value\": 1.0, \"units\": \"%\"},"
                                        "\"heat index\": {\"value\": 1.546666666666666, \"units\": \"°C\"},"
                                        "\"heat index trend\": {\"value\": 0.43333333333333, \"units\": \"°C\"},"
                                        "\"barometer\": {\"value\": 1005.8235273191686, \"units\": \"mbar\"},"
                                        "\"barometer trend\": {\"value\": 0.20536802181527491, \"units\": \"mbar\"},"
                                        "\"wind speed\": {\"value\": 1.0, \"units\": \"km/h\"},"
                                        "\"wind speed trend\": {\"value\": -1.0, \"units\": \"km/h\"},"
                                        "\"wind gust\": {\"value\": 3.1, \"units\": \"km/h\"},"
                                        "\"wind gust trend\": {\"value\": -2.0, \"units\": \"km/h\"},"
                                        "\"wind direction\": {\"value\": 265.35, \"units\": \"°\"},"
                                        "\"rain rate\": {\"value\": 0.0, \"units\": \"mm/h\"},"
                                        "\"rain rate trend\": {\"value\": -0.9599999990207999, \"units\": \"mm/h\"},"
                                        "\"inside temperature\": {\"value\": 20.299999999999986, \"units\": \"°C\"},"
                                        "\"inside humidity\": {\"value\": 48.0, \"units\": \"%\"},"
                                        "\"void_end\": null"
                                        "}"
                        "}";